name: Download ical File
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: init git
      run: |
        sudo apt-get install git
        git init
        git config --local user.email "ldm2060@outlook.com"
        git config --local user.name "dml"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    - name: download
      run: |
        wget -O gy.ics https://w.mdeve.com/101272101.ics
        wget -O cd.ics https://w.mdeve.com/101270119.ics
        sed -i s/PRIVATE/PUBLIC/g ./*.ics
        sed -i ' 4 i X-PUBLISHED-TTL:PT1H\nREFRESH-INTERVAL;VALUE=DURATION:P1H' cd.ics
        sed -i ' 4 i X-PUBLISHED-TTL:PT1H\nREFRESH-INTERVAL;VALUE=DURATION:P1H' gy.ics
        python fix_weather.py
    - name: commit
      run: |
        git add .
        git commit -m "new commit"
        git push -u origin main
   
