name: Download File
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: init git
      run: |
        sudo apt-get install git
        git init
        git clone https://github.com/ldm2060/ical.git
    - name: download
      run: wget -O 1.ics https://w.mdeve.com/101272101.ics
    - name: commit
      run: |
        git add .
        git commit -m "new commit"
        git push -u origin main
   
