name: Download File

on:
  schedule:
    - cron: '51 * * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install download tool
      run: dotnet tool install -g dotnetCampus.FileDownloader.Tool
    - name: Download File
      run: |
          DownloadFile -u https://w.mdeve.com/101272101.ics -o 1.ics
          git add -A
          git diff HEAD --exit-code
          git config --global user.name "github-actions-docfx[bot]"
          git config --global user.email "ldm2060@outlook.com"
          git commit -m "Updated docs from commit $env:GITHUB_SHA on $env:GITHUB_REF"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin gh-pages
