name: Download File
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: init git
      run: |
        sudo apt-get install git
        git init
        git config --local user.email "ldm2060@outlook.com"
        git config --local user.name "dml"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    - name: download
      run: wget -O 1.ics https://w.mdeve.com/101272101.ics
    - name: commit
      run: |
        git add .
        git commit -m "new commit"
        git push -u origin main
   
